// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: espforge_codegen/templates/components.rs

#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]

use core::cell::RefCell;
use espforge_platform::esp_hal::gpio::{AnyPin, Input, Output, Level, Pin, Pull};
use espforge_platform::esp_hal::{Blocking, Async};
pub struct PeripheralRegistry {
    pub sw_interrupt: core::cell::RefCell<
        Option<esp_hal::peripherals::SW_INTERRUPT<'static>>,
    >,
    pub timg0: core::cell::RefCell<Option<esp_hal::peripherals::TIMG0<'static>>>,
    pub wifi: core::cell::RefCell<Option<esp_hal::peripherals::WIFI<'static>>>,
}
impl PeripheralRegistry {
    pub fn new(mut p: espforge_platform::esp_hal::peripherals::Peripherals) -> Self {
        Self {
            sw_interrupt: core::cell::RefCell::new(Some(p.SW_INTERRUPT)),
            timg0: core::cell::RefCell::new(Some(p.TIMG0)),
            wifi: core::cell::RefCell::new(Some(p.WIFI)),
        }
    }
}
pub struct Components {}
impl Components {
    pub fn new(registry: &'static mut PeripheralRegistry) -> Self {
        Self {}
    }
}
pub struct Devices {}
impl Devices {
    pub fn new(
        components: &'static mut Components,
        registry: &'static mut PeripheralRegistry,
        delay: &mut espforge_platform::delay::Delay,
    ) -> Self {
        Self {}
    }
}
pub struct Context {
    pub logger: espforge_platform::logger::Logger,
    pub delay: espforge_platform::delay::Delay,
}
