// USER-OWNED. This file is NOT regenerated by espforge. Edit freely.
//
// Async button example (embassy). Mirrors the v1 `button_async` topology:
// a dedicated `button_task` waits edge-triggered for a press and signals a
// cross-task `Signal`; `forever` waits on that signal and toggles the LED.
//
// Unlike v1 (which used a `static mut COMPONENTS` global), v2 passes the
// `&'static Context` into the spawned task via the generated crate-root `CTX`
// static (`CTX.get()` returns `Option<&'static Context>`). `Button` and `Led`
// both use interior mutability, so a shared `&'static Context` is enough to
// call `wait_for_pressed().await` and `toggle()` from the task.

use crate::{Button, Context, Led};
use embassy_executor::Spawner;

// Cross-task signal (requires the `signal` feature, on for all embassy
// projects). Producer signals; consumer waits.
crate::signal!(BUTTON_PRESSED);

/// Spawned embassy task: waits for the button (edge-triggered, not polled) and
/// signals the LED task to toggle. Runs for the lifetime of the firmware.
#[embassy_executor::task]
async fn button_task(ctx: &'static Context) {
    loop {
        ctx.components.button.wait_for_pressed().await;
        BUTTON_PRESSED.signal(());
    }
}

/// Runs once at startup. Spawn the button-watching task.
pub async fn setup(ctx: &'static Context, spawner: Spawner) {
    spawner.spawn(button_task(ctx).unwrap());
}

/// Per-tick loop. Waits for a press signal, toggles the LED, then debounces.
pub async fn forever(ctx: &'static Context) {
    BUTTON_PRESSED.wait().await;
    ctx.components.red_led.toggle();
    // Debounce: ignore further presses for a short window.
    ctx.delay.delay_ms(100).await;
}
