[package]
name = "espforge_platform"
version = "0.1.4"
edition = "2024"
description = "Platform abstractions for espforge projects"
license = "MIT"
readme = "README.md"
keywords = ["esp32", "embedded", "hal", "framework", "esphome"]
categories = ["embedded", "hardware-support", "no-std"]
repository = "https://github.com/mohankumargupta/espforge"
homepage = "https://github.com/mohankumargupta/espforge"
documentation = "https://github.com/mohankumargupta/espforge"

[dependencies]
embedded-hal = "1.0.0"
embedded-hal-bus = { version = "0.3.0", optional = true }
embedded-io = { version = "0.7.1", optional = true }
log = "0.4"
esp-hal = "1.0.0"
embassy-sync = { version = "0.7", optional = true }
embassy-time = { version = "0.5", optional = true }

[features]
default = []
spi = ["dep:embedded-hal-bus"]
i2c = ["dep:embedded-hal-bus"]
uart = ["dep:embedded-io"]
embassy = ["dep:embassy-sync", "dep:embassy-time"]
esp32 = ["esp-hal/esp32"]
esp32c3 = ["esp-hal/esp32c3"]
esp32c6 = ["esp-hal/esp32c6"]
esp32h2 = ["esp-hal/esp32h2"]
esp32s2 = ["esp-hal/esp32s2"]
esp32s3 = ["esp-hal/esp32s3"]



