use super::constants::AUTOGEN_HEADER;

/// Formats source code with a standard header indicating it is auto-generated
///
/// # Arguments
/// * `source` - The generated source code
/// * `origin` - The file that generated this code
///
/// # Returns
/// Formatted source code with header
pub fn format_generated_source(source: &str, origin: &str) -> String {
    format!("{}\n// Source: {}\n\n{}", AUTOGEN_HEADER, origin, source)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_generated_source() {
        let source = "fn main() {}";
        let origin = "test.rs";
        let result = format_generated_source(source, origin);

        assert!(result.contains("// THIS IS AN AUTOGENERATED FILE"));
        assert!(result.contains("// Source: test.rs"));
        assert!(result.contains("fn main() {}"));
    }

    #[test]
    fn test_format_preserves_source() {
        let source = "use std::collections::HashMap;\n\nfn test() {\n    println!(\"test\");\n}";
        let result = format_generated_source(source, "origin.rs");

        // Original source should be present and unchanged
        assert!(result.contains("use std::collections::HashMap;"));
        assert!(result.contains("fn test()"));
        assert!(result.contains("println!(\"test\")"));
    }
}
