/// Header added to all auto-generated files
pub const AUTOGEN_HEADER: &str = "// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.";

/// Origin paths for different generated file types
pub mod origins {
    pub const LIB: &str = "espforge_codegen/templates/library.rs";
    pub const ENTRY_POINT: &str = "espforge_codegen/templates/entry_point.rs";
    pub const COMPONENTS: &str = "espforge_codegen/templates/components.rs";
}

/// Compiler attributes for allowing unused code
pub const ALLOW_ATTRS: &str = "#![allow(unused_variables)]\n\
                                #![allow(unused_imports)]\n\
                                #![allow(unused_mut)]\n\n";
