[workspace]
resolver = "2"
members = [
    "espforge",
    "espforge_codegen",
    "espforge_common",
    "espforge_components",
    "espforge_components_builder",
    "espforge_configuration",
    "espforge_devices",
    "espforge_devices_builder",
    "espforge_dialogue",
    "espforge_esp32metadata",
    "espforge_examples",
    "espforge_macros",
    "espforge_platform",
]

# exclude = [
#     "espforge_platform",
#     "espforge_components",
#     "espforge_devices"
# ]

default-members = [
    "espforge",
    "espforge_codegen",
    "espforge_common",
    "espforge_components_builder",
    "espforge_configuration",
    "espforge_devices_builder",
    "espforge_dialogue",
    "espforge_esp32metadata",
    "espforge_examples",
    "espforge_macros"
]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/mohankumargupta/espforge"
homepage = "https://github.com/mohankumargupta/espforge"
documentation = "https://github.com/mohankumargupta/espforge"
keywords = ["esp32", "embedded", "hal", "framework", "esphome"]
categories = ["embedded", "hardware-support", "no-std"]

[workspace.dependencies]
espforge_common = { version = "0.1.5", path = "espforge_common" }
espforge_platform = { version = "0.1.11", path = "espforge_platform" }
espforge_components = { version = "0.1.8", path = "espforge_components" }
espforge_devices = { version = "0.1.10", path = "espforge_devices" }
espforge_configuration = { version = "0.3.0", path = "espforge_configuration" }
espforge_codegen = { version = "0.4.0", path = "espforge_codegen" }
espforge_components_builder = { version = "0.1.5", path = "espforge_components_builder" }
espforge_devices_builder = { version = "0.1.5", path = "espforge_devices_builder" }
espforge_dialogue = { version = "0.1.4", path = "espforge_dialogue" }
espforge_esp32metadata = { version = "0.2.3", path = "espforge_esp32metadata" }
espforge_examples = { version = "0.1.5", path = "espforge_examples" }
espforge_macros = { version = "0.1.4", path = "espforge_macros" }

anyhow = "1.0.101"
thiserror = "2.0"
log = "0.4"

serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
serde_yaml_ng = "0.10"
toml = { version = "0.9.8", features = ["preserve_order"] }
toml_edit = "0.23.9"

embedded-hal = "1.0.0"
embedded-hal-bus = "0.3.0"
embedded-io = "0.7.1"
embedded-graphics = "0.8.1"

#esp-hal = "1.0.0"
esp-backtrace = "0.18.1"
esp-println = "0.16.1"

quote = "1.0"
syn = { version = "2.0", features = ["full", "parsing"] }
proc-macro2 = "1.0"
prettyplease = "0.2"

embassy-executor = "0.9.1"
embassy-time = "0.5.0"
embassy-sync = "0.7"

embassy-net = "0.8.0"
reqwless = { version = "0.14", default-features = false }
heapless = "0.9.2"

inventory = "0.3"
static_cell = "2.1"
critical-section = "1.2.0"
include_dir = { version = "0.7.4", features = ["glob"] }

clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.12"
dialogue-macro = "0.3"

ssd1306 = "0.10.0"
ili9341 = "0.6.0"
display-interface-i2c = "0.5.0"
display-interface-spi = "0.5.0"

assert_cmd = "2.1"
assert_fs = "1.1"
predicates = "3.1"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
