// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: espforge_codegen/templates/components.rs

#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]

use core::cell::RefCell;
use espforge_platform::esp_hal::gpio::{AnyPin, Input, Output, Level, Pin, Pull};
use espforge_platform::esp_hal::{Blocking, Async};
pub struct PeripheralRegistry {
    pub sw_interrupt: core::cell::RefCell<
        Option<esp_hal::peripherals::SW_INTERRUPT<'static>>,
    >,
    pub timg0: core::cell::RefCell<Option<esp_hal::peripherals::TIMG0<'static>>>,
    pub gpio9: RefCell<Option<AnyPin<'static>>>,
    pub gpio7: RefCell<Option<AnyPin<'static>>>,
}
impl PeripheralRegistry {
    pub fn new(mut p: espforge_platform::esp_hal::peripherals::Peripherals) -> Self {
        Self {
            sw_interrupt: core::cell::RefCell::new(Some(p.SW_INTERRUPT)),
            timg0: core::cell::RefCell::new(Some(p.TIMG0)),
            gpio9: RefCell::new(Some(p.GPIO9.degrade())),
            gpio7: RefCell::new(Some(p.GPIO7.degrade())),
        }
    }
}
pub struct Components {
    pub button: espforge_components::components::button::Button,
    pub red_led: espforge_components::components::led::component::LED,
}
impl Components {
    pub fn new(registry: &'static mut PeripheralRegistry) -> Self {
        let button = espforge_components::components::button::Button::new(
            espforge_platform::gpio::GPIOInput::from_pin(
                registry.gpio9.borrow_mut().take().unwrap(),
                true,
                false,
            ),
            espforge_components::components::button::ButtonConfig {
                pull_up: true,
                ..Default::default()
            },
        );
        let red_led = espforge_components::components::led::component::LED::new(
            espforge_platform::gpio::GPIOOutput::from_pin(
                registry.gpio7.borrow_mut().take().unwrap(),
            ),
            espforge_components::components::led::component::LedConfig {
                active_low: false,
                ..Default::default()
            },
        );
        Self { button, red_led }
    }
}
pub struct Devices {}
impl Devices {
    pub fn new(
        components: &'static mut Components,
        registry: &'static mut PeripheralRegistry,
        delay: &mut espforge_platform::delay::Delay,
    ) -> Self {
        Self {}
    }
}
pub struct Context {
    pub logger: espforge_platform::logger::Logger,
    pub delay: espforge_platform::delay::Delay,
}
