fun setup() {
    log.info("Initializing ILI9341...")
    log.info("Note, on Wokwi it could take up to 30 seconds to load")
    
    // Initialize
    display.init()
    
    // Draw text
    display.print(10, 10, "Hello World")
    display.print(10, 30, "Generated by Espforge")
}

fun forever() {
    delay.delay_millis(1000)
}



