#[warn(unused_variables)]

use crate::Context;

pub fn setup(ctx: &mut Context) {
    ctx.logger.info("Initializing ILI9341...");
    ctx.logger.info("Note, on Wokwi it could take up to 30 seconds to load");
    
    let display = &mut ctx.devices.display;
    
    display.clear();
    
    // Draw text
    display.print(10, 10, "Hello World");
    display.print(10, 30, "Generated by Espforge");
}

pub fn forever(ctx: &mut Context) {
    ctx.delay.delay_ms(1000);
}



