//! Rust source emitters (ADR-005): pure `fn(&DeviceTree) -> Vec<Artifact>`.
//!
//! These produce the espforge-owned layers of the generated project:
//! - `Cargo.toml`         — depends on `espforge-runtime`; uses a path dep when
//!                           `ESPFORGE_USE_LOCAL` is set (v1 behaviour).
//! - `src/generated.rs`   — `PeripheralRegistry`, `Components`, `Devices` with
//!                           one field per instance, built move-by-value (ADR-008).
//! - `src/lib.rs`         — `#![no_std]` re-exports + `component!`/`device!` macros.
//! - `src/bin/main.rs`    — entry point (blocking or embassy from IR flags).
//! - `src/app.rs`         — user-owned skeleton (`setup`/`forever` hooks).
//!
//! The emitters reference `espforge-runtime` only by *name* in the emitted
//! token stream (ADR-007) — never as a Cargo dependency of the `espforge` host
//! crate.

use anyhow::Result;
use espforge_model::ir::{DeviceTree, ResolvedInstance, Runtime, Tier};
use espforge_model::value::Artifact;
use std::env;

/// Environment variable (v1 behaviour): when set to a local espforge checkout,
/// generated projects depend on local path copies of `espforge-runtime` instead
/// of the published crates.io version.
pub const ESPFORGE_USE_LOCAL: &str = "ESPFORGE_USE_LOCAL";

/// Resolve an `espforge-*` dependency declaration for the generated project's
/// `Cargo.toml`. By default it uses the published crates.io version; when
/// `ESPFORGE_USE_LOCAL` is set (v1 behaviour) it flips to a local path dep into
/// that checkout. Applies uniformly to `espforge-runtime`, `espforge-bindings`,
/// `espforge-model`, etc.
fn espforge_dep(crate_name: &str) -> String {
    match env::var(ESPFORGE_USE_LOCAL) {
        Ok(path) if !path.trim().is_empty() => {
            format!(
                "{crate_name} = {{ path = \"{}/{crate_name}\" }}",
                path.trim_end_matches('/')
            )
        }
        _ => format!("{crate_name} = \"0.1\""),
    }
}

pub fn emit(ir: &DeviceTree) -> Result<Vec<Artifact>> {
    let mut out = Vec::new();
    out.push(Artifact::owned("Cargo.toml", emit_cargo_toml(ir)?));
    out.push(Artifact::owned("src/generated.rs", emit_generated(ir)));
    out.push(Artifact::owned("src/lib.rs", emit_lib(ir)));
    out.push(Artifact::owned("src/bin/main.rs", emit_main(ir)));
    out.push(Artifact::seed_once("src/app.rs", emit_app(ir)));
    Ok(out)
}

fn project_name(ir: &DeviceTree) -> String {
    ir.meta
        .name
        .clone()
        .unwrap_or_else(|| "espforge_project".into())
        .replace('-', "_")
}

fn emit_cargo_toml(ir: &DeviceTree) -> Result<String> {
    let name = project_name(ir);
    let embassy = if ir.flags.is_embassy { "embassy-executor = \"*\"\n" } else { "" };
    let alloc = if ir.flags.has_alloc { "embedded-alloc = \"*\"\n" } else { "" };
    let runtime_dep = espforge_dep("espforge-runtime");
    Ok(format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
{runtime_dep}
esp-hal = "*"
esp-backtrace = "*"
esp-println = "*"
static_cell = "*"
{embassy}{alloc}

[profile.release]
debug = true
"#
    ))
}

fn emit_generated(ir: &DeviceTree) -> String {
    let component_fields = ir
        .instances
        .iter()
        .filter(|i| i.tier == Tier::Component)
        .map(|i| {
            let id = sanitize(&i.id);
            let ty = runtime_type(i);
            format!("    pub {id}: {ty},")
        })
        .collect::<Vec<_>>()
        .join("\n");

    let device_fields = ir
        .instances
        .iter()
        .filter(|i| i.tier == Tier::Device)
        .map(|i| {
            let id = sanitize(&i.id);
            let ty = runtime_type(i);
            format!("    pub {id}: {ty},")
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"// GENERATED BY ESPFORGE — DO NOT EDIT. Source of truth is the project YAML.
#![allow(dead_code)]

/// Raw ESP32 peripherals, moved out of `esp_hal::Peripherals` once at init.
pub struct PeripheralRegistry {{
    pub peripherals: esp_hal::Peripherals,
}}

impl PeripheralRegistry {{
    pub fn new(peripherals: esp_hal::Peripherals) -> Self {{
        Self {{ peripherals }}
    }}
}}

/// Constructed components. Each field is a concrete `espforge_runtime`
/// capability, wired move-by-value from the registry (ADR-008).
pub struct Components {{
{component_fields}
}}

/// Constructed terminal devices.
pub struct Devices {{
{device_fields}
}}
"#
    )
}

fn emit_lib(_ir: &DeviceTree) -> String {
    r#"// GENERATED BY ESPFORGE — DO NOT EDIT. Source of truth is the project YAML.
#![no_std]

pub mod generated;
pub mod app;

pub use generated::{Components, Devices, PeripheralRegistry};

/// Access a component from the generated `Components` struct.
#[macro_export]
macro_rules! component {
    ($name:ident) => {
        &$crate::CTX.components.$name
    };
}

/// Access a device from the generated `Devices` struct.
#[macro_export]
macro_rules! device {
    ($name:ident) => {
        &$crate::CTX.devices.$name
    };
}

/// The whole runtime context the app receives (ADR-008: stable app-facing API).
pub struct Context {
    pub logger: espforge_runtime::Logger,
    pub delay: espforge_runtime::Delay,
    pub components: Components,
    pub devices: Devices,
}

/// Set by the entry point once wiring is complete.
pub static mut CTX: Option<Context> = None;
"#
    .to_string()
}

fn emit_main(ir: &DeviceTree) -> String {
    match ir.meta.runtime {
        Runtime::Embassy => emit_main_embassy(ir),
        Runtime::Blocking => emit_main_blocking(ir),
    }
}

fn emit_main_blocking(ir: &DeviceTree) -> String {
    let _ = ir;
    r#"// GENERATED BY ESPFORGE — DO NOT EDIT. Source of truth is the project YAML.
#![no_std]
#![no_main]

use esp_backtrace as _;
use static_cell::StaticCell;

#[esp_hal::main]
fn main() -> ! {
    esp_println::logger::init_logger_from_env();

    let peripherals = esp_hal::init(esp_hal::Config::default());
    let registry = PeripheralRegistry::new(peripherals);

    // Components are wired move-by-value from the registry (ADR-008).
    let components = Components {
        // populated per-project by the codegen stage
    };
    let devices = Devices {
        // populated per-project by the codegen stage
    };

    let logger = espforge_runtime::Logger::new();
    let delay = espforge_runtime::Delay::new();
    let ctx = Context { logger, delay, components, devices };
    unsafe { crate::CTX = Some(ctx); }

    let ctx = unsafe { crate::CTX.as_mut().unwrap() };
    app::setup(ctx);
    loop {
        app::forever(ctx);
    }
}
"#
    .to_string()
}

fn emit_main_embassy(ir: &DeviceTree) -> String {
    let _ = ir;
    r#"// GENERATED BY ESPFORGE — DO NOT EDIT. Source of truth is the project YAML.
#![no_std]
#![no_main]

use embassy_executor::Spawner;
use esp_backtrace as _;
use esp_hal::interrupt::software::SoftwareInterruptControl;
use esp_hal::timer::timg::TimerGroup;
use static_cell::StaticCell;

#[esp_rtos::main]
async fn main(spawner: Spawner) {
    esp_println::logger::init_logger_from_env();

    let peripherals = esp_hal::init(esp_hal::Config::default());
    let registry = PeripheralRegistry::new(peripherals);

    let sw_int = SoftwareInterruptControl::new(registry.peripherals.sw_interrupt);
    let timg0 = TimerGroup::new(registry.peripherals.TIMG0);
    esp_rtos::start(timg0.timer0, sw_int.software_interrupt0);

    let components = Components {
        // populated per-project by the codegen stage
    };
    let devices = Devices {
        // populated per-project by the codegen stage
    };

    let logger = espforge_runtime::Logger::new();
    let delay = espforge_runtime::Delay::new();
    let ctx = Context { logger, delay, components, devices };
    unsafe { crate::CTX = Some(ctx); }

    let ctx = unsafe { crate::CTX.as_mut().unwrap() };
    app::setup(ctx, spawner).await;
    loop {
        app::forever(ctx).await;
    }
}
"#
    .to_string()
}

fn emit_app(ir: &DeviceTree) -> String {
    let (setup_sig, forever_sig) = if ir.flags.is_embassy {
        (
            "pub async fn setup(ctx: &mut crate::Context, _spawner: Spawner)",
            "pub async fn forever(_ctx: &mut crate::Context)",
        )
    } else {
        (
            "pub fn setup(_ctx: &mut crate::Context)",
            "pub fn forever(_ctx: &mut crate::Context)",
        )
    };
    let embassy_use = if ir.flags.is_embassy {
        "use embassy_executor::Spawner;\n"
    } else {
        ""
    };
    format!(
        r#"// USER-OWNED. This file is NOT regenerated by espforge. Edit freely.
{embassy_use}
{setup_sig} {{
    // espforge wired your components/devices; access them via `component!`/`device!`.
}}

{forever_sig} {{
    // your loop body here
}}
"#
    )
}

/// Map a driver `kind` to its `espforge_runtime` type name. Components live in
/// `espforge_runtime::components`, devices in `espforge_runtime::devices` (ADR-007).
/// The PascalCase type name is derived from the kind; the canonical mapping is
/// owned by the driver registry. This is the codegen mirror.
fn runtime_type(inst: &ResolvedInstance) -> String {
    let pascal = inst
        .kind
        .split(['-', '_'])
        .map(|s| {
            let mut c = s.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect::<String>();
    match inst.tier {
        Tier::Component => format!("espforge_runtime::components::{pascal}"),
        Tier::Device => format!("espforge_runtime::devices::{pascal}"),
    }
}

/// Sanitize an instance id into a Rust identifier.
fn sanitize(id: &str) -> String {
    let mut out = String::new();
    for (i, c) in id.chars().enumerate() {
        if c.is_alphanumeric() && (i == 0 && c.is_alphabetic() || i > 0) {
            out.push(c);
        } else if i > 0 {
            out.push('_');
        }
    }
    if out.is_empty() {
        out = "inst".to_string();
    }
    out
}
