[package]
name = "espforge_components"
version = "0.1.12"
description = "Components for espforge"
edition.workspace = true
license.workspace = true
readme.workspace = true 
keywords.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true
documentation.workspace = true

[dependencies]
espforge_common = { version = "0.1.7", path = "../espforge_common", default-features = false }
espforge_platform = { version = "0.1.14", path = "../espforge_platform" }
embedded-hal = "1.0.0"
embedded-io = { version = "0.7.1", optional = true }
reqwless = { workspace = true, optional = true, default-features = false}
heapless = { workspace = true, optional = true }

[features]
default = []
i2c = [ "espforge_platform/i2c" ]
spi = [ "espforge_platform/spi" ]
uart = ["dep:embedded-io", "espforge_platform/uart"]
button = []
led = []
http = ["dep:reqwless", "dep:heapless", "espforge_platform/wifi"]
std = ["espforge_common/std"]
embassy = ["espforge_platform/embassy"]
websocket = ["dep:heapless", "espforge_platform/wifi", "espforge_platform/tls"]



[package.metadata.dist]
dist = false
