[package]
name = "espforge_components"
version = "0.1.5"
description = "Components for espforge"
edition.workspace = true
license.workspace = true
readme.workspace = true 
keywords.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true
documentation.workspace = true

[dependencies]
espforge_common = { version = "0.1.2", path = "../espforge_common", default-features = false }
espforge_platform = { version = "0.1.8", path = "../espforge_platform" }
embedded-hal = "1.0.0"
embedded-io = { version = "0.7.1", optional = true }

[features]
default = []
i2c = [ "espforge_platform/i2c" ]
spi = [ "espforge_platform/spi" ]
uart = ["dep:embedded-io", "espforge_platform/uart"]
button = []
led = []
std = ["espforge_common/std"]
embassy = ["espforge_platform/embassy"]

[package.metadata.dist]
dist = false
