[package]
name = "espforge_examples"
version = "0.1.1"
description = "Embedded examples for espforge"
edition.workspace = true
license.workspace = true
readme.workspace = true 
keywords.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true
documentation.workspace = true

[dependencies]
include_dir = { version = "0.7.4", features = ["glob"] }

