[package]
name = "espforge_devices_builder"
version = "0.1.5"
description = "Component registration for espforge"
edition.workspace = true
license.workspace = true
readme.workspace = true 
keywords.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true
documentation.workspace = true

[dependencies]
espforge_common = { version = "0.1.5", path = "../espforge_common" }
espforge_configuration = { path = "../espforge_configuration", version = "0.3.0" }
espforge_macros = { path = "../espforge_macros", version = "0.1.4" }
anyhow = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml_ng = "0.10"
inventory = "0.3"
syn = "2.0"

