pub mod builders;
pub mod component_builders;
pub mod generator;
pub mod scaffold;

use anyhow::{Context, Result};
use quote::quote;
use espforge_common::EspforgeConfiguration;

// Re-export specific items for convenience
pub use scaffold::esp_generate;

/// Main entry point: Generates the entire `generated.rs` content
pub fn generate_components_source(model: &EspforgeConfiguration) -> Result<String> {
    // Generate the struct that owns the raw silicon
    let hardware_struct = generator::hardware::generate_peripheral_registry(model)?;

    // Generate the struct that owns the platform components
    let components_struct = generator::components::generate_component_registry(model)?;

    let output = quote! {
        // Generated by espforge
        #[allow(unused_imports)]

        use esp_hal::{
            gpio::{AnyPin, Io},
            spi::{master::Spi, Mode},
            i2c::master::I2c,
            peripherals::Peripherals,
            Blocking,
        };
        use core::cell::RefCell;
        use core::marker::PhantomData;
        use esp_hal::gpio::Pin;

        // Platform dependencies for the Component Registry
        use crate::platform;

        #hardware_struct

        #components_struct
    };

    let syntax_tree = syn::parse2(output).context("Failed to parse generated tokens")?;
    Ok(prettyplease::unparse(&syntax_tree))
}
