pub mod builders;
pub mod component_builders;
pub mod generator;
pub mod scaffold;

use anyhow::{Context, Result};
use espforge_common::EspforgeConfiguration;
use quote::quote;

// Re-export specific items for convenience
pub use scaffold::esp_generate;

/// Main entry point: Generates the entire `generated.rs` content
pub fn generate_components_source(model: &EspforgeConfiguration) -> Result<String> {
    // Generate the struct that owns the raw silicon
    let hardware_struct = generator::hardware::generate_peripheral_registry(model)?;

    // Generate the struct that owns the platform components
    let components_struct = generator::components::generate_component_registry(model)?;

    let devices_struct = generator::devices::generate_device_registry(model)?;

    let output = quote! {
        // Generated by espforge
        #[allow(unused_imports)]

        use esp_hal::{
            gpio::{AnyPin, Io, Pin, Output, Input, Level, OutputConfig, InputConfig, Pull},
            spi::{master::Spi, Mode},
            i2c::master::I2c,
            peripherals::Peripherals,
            Blocking,
        };
        use core::cell::RefCell;
        use core::marker::PhantomData;

        // Platform dependencies for the Component Registry
        use espforge_platform as platform;

        #hardware_struct

        pub mod ergonomics {
            use embedded_hal::digital::{StatefulOutputPin, InputPin, OutputPin};

            /// Adds simple .on() .off() .toggle() methods that panic on error
            /// instead of returning Result.
            pub trait EasyOutput: StatefulOutputPin {
                fn on(&mut self) {
                    self.set_high().unwrap_or_else(|_| panic!("GPIO Error"));
                }

                fn off(&mut self) {
                    self.set_low().unwrap_or_else(|_| panic!("GPIO Error"));
                }

                fn toggle(&mut self) {
                    StatefulOutputPin::toggle(self).unwrap_or_else(|_| panic!("GPIO Error"));
                }
            }

            // Blanket implementation: This applies the trait to ANY pin that implements the standard trait
            impl<T: StatefulOutputPin> EasyOutput for T {}

            /// Adds simple .is_pressed() logic
            pub trait EasyInput: InputPin {
                fn is_pressed(&mut self) -> bool {
                    // Default to active low (pull-up) common for buttons
                    self.is_low().unwrap_or(false)
                }

                fn is_released(&mut self) -> bool {
                    self.is_high().unwrap_or(false)
                }
            }

            impl<T: InputPin> EasyInput for T {}
        }


        #components_struct

        #devices_struct
    };

    let syntax_tree = syn::parse2(output).context("Failed to parse generated tokens")?;
    Ok(prettyplease::unparse(&syntax_tree))
}
