use crate::context::CodegenContext;
use anyhow::{Context as _, Result};
use espforge_configuration::EspforgeConfiguration;
use espforge_configuration::RuntimeMode;
use prettyplease;
use quote::format_ident;
use quote::quote;
use syn;

pub mod builders;
pub mod component_builders;
pub mod context;
pub mod dependency;
pub mod generator;
pub mod registry;
pub mod resolver;
pub mod scaffold;

pub use scaffold::esp_generate;

pub fn generate_lib_source(additional_modules: &[String]) -> Result<String> {
    let mut mod_declarations = quote! {};
    for module in additional_modules {
        let mod_ident = format_ident!("{}", module);
        mod_declarations.extend(quote! {
            pub mod #mod_ident;
        });
    }
    let tokens = quote! {
        #![no_std]

        #mod_declarations
        pub mod generated;
        pub mod app;

        pub use generated::*;
        pub use espforge_platform::Context;

        // Global static references to the initialized components and devices
        // These are set up in the main entry point and accessed through macros
        pub static mut REGISTRY: *mut PeripheralRegistry = core::ptr::null_mut();
        pub static mut COMPONENTS: *mut Components = core::ptr::null_mut();
        pub static mut DEVICES: *mut Devices = core::ptr::null_mut();

        // ============================================================
        // Inline Macros for Component and Device Access
        // ============================================================

        /// Access a component from the global static registry
        ///
        /// # Example
        /// ```
        /// let led = component!(ctx, red_led);
        /// led.toggle();
        /// ```
        #[macro_export]
        macro_rules! component {
            ($name:ident) => {
                unsafe { &mut (*$crate::COMPONENTS).$name }
            };
        }

        /// Access a device from the global static registry
        ///
        /// # Example
        /// ```
        /// let oled = device!(ctx, oled);
        /// oled.clear();
        /// ```
        #[macro_export]
        macro_rules! device {
            ($name:ident) => {
                unsafe { &mut (*$crate::DEVICES).$name }
            };
        }

        /// Execute a closure with mutable access to a component
        ///
        /// # Example
        /// ```
        /// with_component!(ctx, red_led, |led| {
        ///     led.toggle();
        /// });
        /// ```
        #[macro_export]
        macro_rules! with_component {
            ($name:ident, |$var:ident| $body:block) => {{
                let $var = unsafe { &mut (*$crate::COMPONENTS).$name };
                $body
            }};
        }

        /// Execute a closure with mutable access to a device
        ///
        /// # Example
        /// ```
        /// with_device!(ctx, oled, |display| {
        ///     display.clear();
        ///     display.print(0, 0, "Hello!");
        /// });
        /// ```
        #[macro_export]
        macro_rules! with_device {
            ($name:ident, |$var:ident| $body:block) => {{
                let $var = unsafe { &mut (*$crate::DEVICES).$name };
                $body
            }};
        }
    };

    let syntax_tree = syn::parse2(tokens).context("Failed to parse generated library structure")?;
    let content = prettyplease::unparse(&syntax_tree);
    Ok(format!(
        "// THIS IS A AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n// Source: espforge_codegen/src/lib.rs::generate_lib_source\n\n{}",
        content
    ))
}

pub fn generate_entry_point_source(model: &EspforgeConfiguration) -> Result<String> {
    let code = match model.get_runtime() {
        RuntimeMode::Embassy => generate_embassy_entry_point(model)?,
        RuntimeMode::None => generate_blocking_entry_point(model)?,
    };
    Ok(format!(
        "// THIS IS A AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n// Source: espforge_codegen/src/lib.rs::generate_entry_point_source\n\n{}",
        code
    ))
}

fn generate_blocking_entry_point(model: &EspforgeConfiguration) -> Result<String> {
    let crate_name = model.get_name().replace('-', "_");
    let crate_ident = format_ident!("{}", crate_name);

    // Generate heap allocator with chip-specific size
    let heap_allocator = if let Some(size) = model.get_heap_size() {
        quote! {
            esp_alloc::heap_allocator!(#[esp_hal::ram(reclaimed)] size: #size);
        }
    } else {
        quote! {}
    };

    let psram_allocator = if model.has_psram() == Some(true) {
        quote! {
            esp_alloc::psram_allocator!(peripherals.PSRAM, esp_hal::psram);
        }
    } else {
        quote! {}
    };

    let tokens = quote! {
        #![no_std]
        #![no_main]

        use esp_backtrace as _;
        use #crate_ident::*;
        use static_cell::StaticCell;

        // Static storage cells - initialized once at startup
        static REGISTRY_CELL: StaticCell<PeripheralRegistry> = StaticCell::new();
        static COMPONENTS_CELL: StaticCell<Components> = StaticCell::new();
        static DEVICES_CELL: StaticCell<Devices> = StaticCell::new();

        #[esp_hal::main]
        fn main() -> ! {
            esp_println::logger::init_logger_from_env();
            esp_println::print!("\x1b[20h");
            // Initialize peripherals
            let peripherals = esp_hal::init(esp_hal::Config::default());

             #heap_allocator

             #psram_allocator

            // Initialize registry with static lifetime
            let registry = REGISTRY_CELL.init(PeripheralRegistry::new(peripherals));
            unsafe { REGISTRY = registry as *mut _; }

            // Initialize components with static lifetime
            // Components take ownership from registry
            let components = COMPONENTS_CELL.init(
                Components::new(unsafe { &mut *REGISTRY })
            );
            unsafe { COMPONENTS = components as *mut _; }

            // Initialize devices with static lifetime
            // Devices use components and take pins from registry
            let mut delay = espforge_platform::delay::Delay::new();
            let devices = DEVICES_CELL.init(
                Devices::new(
                    unsafe { &mut *COMPONENTS },
                    unsafe { &mut *REGISTRY },
                    &mut delay
                )
            );
            unsafe { DEVICES = devices as *mut _; }

            // Create context (only contains utilities)
            let logger = espforge_platform::logger::Logger::new();
            let mut ctx = Context {
                logger,
                delay,
            };

            // Run user setup
            app::setup(&mut ctx);

            // Run user loop forever
            loop {
                app::forever(&mut ctx);
            }
        }
    };

    let syntax_tree = syn::parse2(tokens)?;
    Ok(prettyplease::unparse(&syntax_tree))
}

fn generate_embassy_entry_point(model: &EspforgeConfiguration) -> Result<String> {
    let crate_name = model.get_name().replace('-', "_");
    let crate_ident = format_ident!("{}", crate_name);

    // Generate heap allocator with chip-specific size
    let heap_allocator = if let Some(size) = model.get_heap_size() {
        quote! {
            esp_alloc::heap_allocator!(#[esp_hal::ram(reclaimed)] size: #size);
        }
    } else {
        quote! {}
    };

    let psram_allocator = if model.has_psram() == Some(true) {
        quote! {
            esp_alloc::psram_allocator!(peripherals.PSRAM, esp_hal::psram);
        }
    } else {
        quote! {}
    };

    

    let tokens = quote! {
        #![no_std]
        #![no_main]

        use esp_backtrace as _;
        use embassy_executor::Spawner;
        use #crate_ident::*;
        use static_cell::StaticCell;
        use esp_hal::interrupt::software::SoftwareInterruptControl;
        use esp_hal::timer::timg::TimerGroup;

        // Static storage cells
        static REGISTRY_CELL: StaticCell<PeripheralRegistry> = StaticCell::new();
        static COMPONENTS_CELL: StaticCell<Components> = StaticCell::new();
        static DEVICES_CELL: StaticCell<Devices> = StaticCell::new();

        #[esp_rtos::main]
        async fn main(spawner: Spawner) {
            esp_println::logger::init_logger_from_env();
            esp_println::print!("\x1b[20h");
            // Initialize peripherals
            let peripherals = esp_hal::init(esp_hal::Config::default());

            

            #heap_allocator

            #psram_allocator

            // Initialize registry
            let registry = REGISTRY_CELL.init(PeripheralRegistry::new(peripherals));
            unsafe { REGISTRY = registry as *mut _; }

            let sw_int_raw = registry.sw_interrupt.borrow_mut().take().expect("SW_INTERRUPT missing");
            let timg0_raw = registry.timg0.borrow_mut().take().expect("timg0 missing");
            let sw_int = SoftwareInterruptControl::new(sw_int_raw);
            let timg0 = TimerGroup::new(timg0_raw);
            esp_rtos::start(timg0.timer0, sw_int.software_interrupt0);

            // Initialize components
            let components = COMPONENTS_CELL.init(
                Components::new(unsafe { &mut *REGISTRY })
            );
            unsafe { COMPONENTS = components as *mut _; }

            // Initialize devices
            let mut delay = espforge_platform::delay::Delay::new();
            let devices = DEVICES_CELL.init(
                Devices::new(
                    unsafe { &mut *COMPONENTS },
                    unsafe { &mut *REGISTRY },
                    &mut delay
                )
            );
            unsafe { DEVICES = devices as *mut _; }

            // Create context
            let logger = espforge_platform::logger::Logger::new();
            let mut ctx = Context {
                logger,
                delay,
            };

            // Run user setup
            app::setup(&mut ctx, spawner).await;

            // Run user loop forever
            loop {
                app::forever(&mut ctx).await;
            }
        }

        // #[panic_handler]
        // fn panic(info: &core::panic::PanicInfo) -> ! {
        //     esp_println::println!("Panic: {:?}", info);
        //     loop {}
        // }
    };

    let syntax_tree = syn::parse2(tokens)?;
    Ok(prettyplease::unparse(&syntax_tree))
}

pub fn generate_components_source(model: &EspforgeConfiguration) -> Result<String> {
    let ctx = CodegenContext::build(model)?;
    let tokens = ctx.generate()?;

    // Determine enabled features based on configuration
    let has_spi = model.esp32.as_ref().map_or(false, |p| !p.spi.is_empty());
    let has_i2c = model.esp32.as_ref().map_or(false, |p| !p.i2c.is_empty());

    // Base imports required for all projects
    let mut imports = quote! {
        use core::cell::RefCell;
        use espforge_platform::esp_hal::gpio::{AnyPin, Input, Output, Level, Pin, Pull};
        use espforge_platform::esp_hal::{Blocking, Async};
    };

    // Conditionally add SPI imports
    if has_spi {
        imports.extend(quote! {
            use espforge_platform::esp_hal::spi::master::Spi;
            use espforge_platform::bus::SpiDevice;
            use embedded_hal_bus::spi::RefCellDevice as SpiRefCellDevice;
        });
    }

    // Conditionally add I2C imports
    if has_i2c {
        imports.extend(quote! {
            use espforge_platform::esp_hal::i2c::master::I2c;
        });

        // Currently, espforge_platform gates the `bus` module behind the `spi` feature.
        // We only import I2cDevice from `bus` if SPI is also enabled (or if the platform is fixed).
        // For now, this logic aligns with the existing platform constraints.
        if has_spi {
            imports.extend(quote! {
                use espforge_platform::bus::I2cDevice;
                use embedded_hal_bus::i2c::RefCellDevice as I2cRefCellDevice;
            });
        }
    }

    let output = quote! {
        #imports
        #tokens
    };

    if let Err(e) = syn::parse2::<syn::File>(output.clone()) {
        println!("---------------------------------------------------");
        println!("DEBUG: Generated Code causing syntax error:");
        println!("Error: {}", e);
        println!("{}", output);
        println!("---------------------------------------------------");
        return Err(anyhow::anyhow!("Failed to parse generated tokens: {}", e));
    }

    let syntax_tree = syn::parse2(output).context("Failed to parse generated tokens")?;
    let content = prettyplease::unparse(&syntax_tree);
    Ok(format!(
        "// THIS IS A AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n// Source: espforge_codegen/src/lib.rs::generate_components_source\n\n#![allow(unused_variables)]\n#![allow(unused_imports)]\n#![allow(unused_mut)]\n\n{}",
        content
    ))
}
