// THIS IS A AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: espforge_codegen/src/lib.rs::generate_components_source

#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]

use core::cell::RefCell;
use espforge_platform::esp_hal::gpio::{AnyPin, Input, Output, Level, Pin, Pull};
use espforge_platform::esp_hal::{Blocking, Async};
pub struct PeripheralRegistry {
    pub gpio2: RefCell<Option<AnyPin<'static>>>,
}
impl PeripheralRegistry {
    pub fn new(mut p: espforge_platform::esp_hal::peripherals::Peripherals) -> Self {
        Self {
            gpio2: RefCell::new(Some(p.GPIO18.degrade())),
        }
    }
}
pub struct Components {
    pub red_led: espforge_components::components::led::component::LED,
}
impl Components {
    pub fn new(registry: &'static mut PeripheralRegistry) -> Self {
        let red_led = espforge_components::components::led::component::LED::new(
            espforge_platform::gpio::GPIOOutput::from_pin(
                registry.gpio2.borrow_mut().take().unwrap(),
            ),
            espforge_components::components::led::component::LedConfig {
                active_low: false,
                ..Default::default()
            },
        );
        Self { red_led }
    }
}
pub struct Devices {}
impl Devices {
    pub fn new(
        components: &'static mut Components,
        registry: &'static mut PeripheralRegistry,
        delay: &mut espforge_platform::delay::Delay,
    ) -> Self {
        Self {}
    }
}
pub struct Context {
    pub logger: espforge_platform::logger::Logger,
    pub delay: espforge_platform::delay::Delay,
}
