// GENERATED BY ESPFORGE — DO NOT EDIT. Source of truth is the project YAML.
#![allow(dead_code)]

/// Raw ESP32 peripherals, moved out of `esp_hal::peripherals::Peripherals` once at init.
pub struct PeripheralRegistry {
    pub peripherals: esp_hal::peripherals::Peripherals,
}

impl PeripheralRegistry {
    pub fn new(peripherals: esp_hal::peripherals::Peripherals) -> Self {
        Self { peripherals }
    }
}

/// Constructed components. Each field is a concrete `espforge_runtime`
/// capability, wired move-by-value from the registry (ADR-008).
pub struct Components {
    pub red_led: espforge_runtime::components::Led,
}

/// Constructed terminal devices.
pub struct Devices {

}
