// GENERATED BY ESPFORGE — DO NOT EDIT. Source of truth is the project YAML.
#![no_std]

pub mod generated;
pub mod app;

pub use generated::{Components, Devices, PeripheralRegistry};

/// Access a component from a `Context`'s generated `Components` struct.
/// Usage: `component!(ctx, my_led)`#[macro_export]
macro_rules! component {
    ($ctx:expr, $name:ident) => {
        &$ctx.components.$name
    };
}

/// Access a device from a `Context`'s generated `Devices` struct.
/// Usage: `device!(ctx, my_screen)`#[macro_export]
macro_rules! device {
    ($ctx:expr, $name:ident) => {
        &$ctx.devices.$name
    };
}

/// The whole runtime context the app receives (ADR-008: stable app-facing API).
pub struct Context {
    pub logger: espforge_runtime::Logger,
    pub delay: espforge_runtime::Delay,
    pub components: Components,
    pub devices: Devices,
}

/// Set by the entry point once wiring is complete.
pub static CTX: static_cell::StaticCell<Context> = static_cell::StaticCell::new();
