// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: espforge_codegen/templates/library.rs

#![no_std]
pub mod app;
pub mod generated;
pub use generated::{Components, Devices, PeripheralRegistry};
pub use espforge_platform::Context;
pub static mut REGISTRY: *mut PeripheralRegistry = core::ptr::null_mut();
pub static mut COMPONENTS: *mut Components = core::ptr::null_mut();
pub static mut DEVICES: *mut Devices = core::ptr::null_mut();
/// Access a component from the global static registry
#[macro_export]
macro_rules! component {
    ($name:ident) => {
        unsafe { & mut (* $crate::COMPONENTS). $name }
    };
}
/// Access a device from the global static registry
#[macro_export]
macro_rules! device {
    ($name:ident) => {
        unsafe { & mut (* $crate::DEVICES). $name }
    };
}
/// Execute a closure with mutable access to a component
#[macro_export]
macro_rules! with_component {
    ($name:ident, | $var:ident | $body:block) => {
        { let $var = unsafe { & mut (* $crate::COMPONENTS). $name }; $body }
    };
}
/// Execute a closure with mutable access to a device
#[macro_export]
macro_rules! with_device {
    ($name:ident, | $var:ident | $body:block) => {
        { let $var = unsafe { & mut (* $crate::DEVICES). $name }; $body }
    };
}
