[package]
name = "espforge_codegen"
version = "0.4.5"
description = "code generation for espforge"
edition.workspace = true
license.workspace = true
readme.workspace = true 
keywords.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true
documentation.workspace = true

[dependencies]
espforge_common = { version = "0.1.7", path = "../espforge_common" }
espforge_configuration = { path = "../espforge_configuration", version = "0.3.4" }
quote = "1.0"
proc-macro2 = "1.0"
prettyplease = "0.2" 
syn = { version = "2.0", features = ["full", "parsing"] }
anyhow = "1.0"
serde_yaml_ng="0.10"
inventory = "0.3"
