use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let devices_dir = Path::new(&manifest_dir).join("src").join("devices");
    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("device_exports.rs");

    println!("cargo:rerun-if-changed=src/devices");

    let mut lines: Vec<String> = vec!["// AUTO-GENERATED by build.rs — do not edit".to_string()];

    let mut entries: Vec<_> = fs::read_dir(&devices_dir)
        .expect("Failed to read src/devices")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();

    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let module_name = entry.file_name().to_string_lossy().to_string();
        let device_rs = entry.path().join("device.rs");

        println!(
            "cargo:rerun-if-changed=src/devices/{}/device.rs",
            module_name
        );

        if !device_rs.exists() {
            continue;
        }

        let source = fs::read_to_string(&device_rs)
            .unwrap_or_else(|_| panic!("Failed to read {}", device_rs.display()));

        let pub_types: Vec<String> = source
            .lines()
            .filter_map(|line| {
                let trimmed = line.trim();
                // Match: pub struct Foo  or  pub enum Foo
                let rest = trimmed
                    .strip_prefix("pub struct ")
                    .or_else(|| trimmed.strip_prefix("pub enum "))?;
                // Take the identifier up to the first '<', '{', '(' or whitespace
                let name: String = rest
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '_')
                    .collect();
                if name.is_empty() { None } else { Some(name) }
            })
            .collect();

        if pub_types.is_empty() {
            continue;
        }

        let types_joined = pub_types.join(", ");
        lines.push(format!(
            "#[cfg(feature = \"{module_name}\")] pub use crate::devices::{module_name}::device::{{{types_joined}}};"
        ));
    }

    fs::write(&out_path, lines.join("\n") + "\n").expect("Failed to write device_exports.rs");
}
