[package]
name = "espforge_devices"
version = "0.1.11"
description = "Devices for espforge"
edition.workspace = true
license.workspace = true
readme.workspace = true 
keywords.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true
documentation.workspace = true

[dependencies]
espforge_platform = { version = "0.1.12", path = "../espforge_platform" }
ssd1306 = { version = "0.10.0", optional = true }
ili9341 = { version = "0.6.0", optional = true }
embedded-graphics.workspace = true
embedded-hal.workspace = true
display-interface-i2c = { version = "0.5.0", optional = true }
display-interface-spi = { version = "0.5.0", optional = true }

[features]
ssd1306 = ["dep:ssd1306", "dep:display-interface-i2c"]
ili9341 = ["dep:ili9341", "dep:display-interface-spi"]
ft6206 = []

[package.metadata.dist]
dist = false

