[package]
name = "espforge_devices"
version = "0.1.2"
edition = "2024"
description = "Devices for espforge"
license = "MIT"
readme = "README.md"
keywords = ["esp32", "embedded", "hal", "framework", "esphome"]
categories = ["embedded", "hardware-support", "no-std"]
repository = "https://github.com/mohankumargupta/espforge"
homepage = "https://github.com/mohankumargupta/espforge"
documentation = "https://github.com/mohankumargupta/espforge"


[dependencies]
espforge_platform = {version="0.1.2", path = "../espforge_platform" }
ssd1306 = "0.10.0"
ili9341 = "0.6.0"
display-interface-spi = "0.5.0"
embedded-graphics = "0.8.1"
embedded-hal = "1.0.0"
display-interface-i2c = "0.5.0"

[workspace]
