// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: espforge_codegen/templates/components.rs

#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]

use core::cell::RefCell;
use espforge_platform::esp_hal::gpio::{AnyPin, Input, Output, Level, Pin, Pull};
use espforge_platform::esp_hal::{Blocking, Async};
pub struct PeripheralRegistry {}
impl PeripheralRegistry {
    pub fn new(mut p: espforge_platform::esp_hal::peripherals::Peripherals) -> Self {
        Self {}
    }
}
pub struct Components {}
impl Components {
    pub fn new(registry: &'static mut PeripheralRegistry) -> Self {
        Self {}
    }
}
pub struct Devices {}
impl Devices {
    pub fn new(
        components: &'static mut Components,
        registry: &'static mut PeripheralRegistry,
        delay: &mut espforge_platform::delay::Delay,
    ) -> Self {
        Self {}
    }
}
pub struct Context {
    pub logger: espforge_platform::logger::Logger,
    pub delay: espforge_platform::delay::Delay,
}
