[package]
name = "espforge_esp32metadata"
version = "0.2.0"
description = "Embedded examples for espforge"
edition.workspace = true
license.workspace = true
readme.workspace = true 
keywords.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true
documentation.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"

[build-dependencies]
toml = "0.9"

