#[warn(unused_variables)]

use crate::{Context, device};

pub fn setup(ctx: &mut Context) {
    let logger = ctx.logger;
    let display = device!(display);

    logger.info("Initializing ILI9341...");
    logger.info("Note, on Wokwi it could take up to 30 seconds to load");
    
    display.clear();
    display.print(10, 10, "Hello World");
    display.print(10, 30, "Generated by Espforge");
}

pub fn forever(ctx: &mut Context) {
    let delay = ctx.delay;
    
    delay.delay_ms(1000);
}



