[package]
name = "espforge_common"
version = "0.1.6"
description = "Configuration model for espforge"
edition.workspace = true
license.workspace = true
readme.workspace = true 
keywords.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true
documentation.workspace = true

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }

[features]
default = ["std", "serde"]
std = ["serde/std"]
serde = []






