// USER-OWNED. This file is NOT regenerated by espforge. Edit freely.
use embassy_executor::Spawner;

pub async fn setup(ctx: &mut crate::Context, _spawner: Spawner) {
    // espforge wired your components/devices; access them via `crate::component!`/`crate::device!`.
}

pub async fn forever(_ctx: &mut crate::Context) {
    // your async loop body here — drive the SSD1306 `screen` device.
}
