#[warn(unused_variables)]

use esp_hal::delay::Delay;

use mousefood::{EmbeddedBackend, EmbeddedBackendConfig};
use ratatui::Terminal;

use crate::{Context, device, menu::MenuApp};

pub fn setup(ctx: &mut Context) {
    let logger = ctx.logger;
    let display = device!(display);

    logger.info("Initializing ILI9341...");
    logger.info("Note, on Wokwi it could take up to 30 seconds to load");
    
    display.clear();
    // display.print(10, 10, "Hello World");
    // display.print(10, 30, "Generated by Espforge");

    let backend = EmbeddedBackend::new(display, EmbeddedBackendConfig::default());
    let mut terminal = Terminal::new(backend).unwrap();
    let delay = Delay::new();
    MenuApp::new().run(&mut terminal, &delay);
}

pub fn forever(ctx: &mut Context) {
    let delay = ctx.delay;
    
    delay.delay_ms(1000);
}


