// THIS IS A AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: espforge_codegen/src/lib.rs::generate_components_source

#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]

use core::cell::RefCell;
use espforge_platform::esp_hal::gpio::{AnyPin, Input, Output, Level, Pin, Pull};
use espforge_platform::esp_hal::{Blocking, Async};
use espforge_platform::esp_hal::spi::master::Spi;
use espforge_platform::bus::SpiDevice;
use embedded_hal_bus::spi::RefCellDevice as SpiRefCellDevice;
pub struct PeripheralRegistry {
    pub pin_cs: RefCell<Option<AnyPin<'static>>>,
    pub pin_dc: RefCell<Option<AnyPin<'static>>>,
    pub pin_rst: RefCell<Option<AnyPin<'static>>>,
    pub spi2: RefCell<Spi<'static, Blocking>>,
}
impl PeripheralRegistry {
    pub fn new(mut p: espforge_platform::esp_hal::peripherals::Peripherals) -> Self {
        let mut spi2 = espforge_platform::esp_hal::spi::master::Spi::new(
                p.SPI2,
                espforge_platform::esp_hal::spi::master::Config::default()
                    .with_frequency(
                        espforge_platform::esp_hal::time::Rate::from_khz(10000u32),
                    )
                    .with_mode(espforge_platform::esp_hal::spi::Mode::_0),
            )
            .expect("Failed to initialize SPI")
            .with_sck(p.GPIO3)
            .with_mosi(p.GPIO4);
        Self {
            pin_cs: RefCell::new(Some(p.GPIO5.degrade())),
            pin_dc: RefCell::new(Some(p.GPIO6.degrade())),
            pin_rst: RefCell::new(Some(p.GPIO7.degrade())),
            spi2: RefCell::new(spi2),
        }
    }
}
pub struct Components {
    pub main_spi: espforge_components::components::spi::SPI,
}
impl Components {
    pub fn new(registry: &'static mut PeripheralRegistry) -> Self {
        let main_spi = espforge_components::components::spi::SPI::new(&registry.spi2);
        Self { main_spi }
    }
}
pub struct Devices {
    pub display: espforge_devices::devices::ili9341::device::ILI9341Device<
        espforge_platform::bus::SpiDevice<'static>,
        espforge_platform::gpio::GPIOOutput,
        espforge_platform::gpio::GPIOOutput,
    >,
}
impl Devices {
    pub fn new(
        components: &'static mut Components,
        registry: &'static mut PeripheralRegistry,
        delay: &mut espforge_platform::delay::Delay,
    ) -> Self {
        let display_dc_pin = registry
            .pin_dc
            .borrow_mut()
            .take()
            .expect("DC pin already in use");
        let display_rst_pin = registry
            .pin_rst
            .borrow_mut()
            .take()
            .expect("RST pin already in use");
        let display_cs_pin = registry
            .pin_cs
            .borrow_mut()
            .take()
            .expect("CS pin already in use");
        let display_dc_pin = espforge_platform::gpio::GPIOOutput::from_pin(
            display_dc_pin,
        );
        let display_rst_pin = espforge_platform::gpio::GPIOOutput::from_pin(
            display_rst_pin,
        );
        let mut display_cs_pin = espforge_platform::gpio::GPIOOutput::from_pin(
            display_cs_pin,
        );
        {
            use embedded_hal::digital::OutputPin;
            display_cs_pin.set_high().ok();
        }
        let display_spi_dev = espforge_platform::bus::SpiDevice::new(
            components.main_spi.bus(),
            display_cs_pin,
        );
        let display = espforge_devices::devices::ili9341::device::ILI9341Device::new(
            display_spi_dev,
            display_dc_pin,
            display_rst_pin,
            delay,
        );
        Self { display }
    }
}
pub struct Context {
    pub logger: espforge_platform::logger::Logger,
    pub delay: espforge_platform::delay::Delay,
}
