// THIS IS A AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: espforge_codegen/src/lib.rs::generate_lib_source

#![no_std]
pub mod menu;
pub mod generated;
pub mod app;
pub use generated::*;
pub use espforge_platform::Context;
pub static mut REGISTRY: *mut PeripheralRegistry = core::ptr::null_mut();
pub static mut COMPONENTS: *mut Components = core::ptr::null_mut();
pub static mut DEVICES: *mut Devices = core::ptr::null_mut();
/// Access a component from the global static registry
///
/// # Example
/// ```
/// let led = component!(ctx, red_led);
/// led.toggle();
/// ```
#[macro_export]
macro_rules! component {
    ($name:ident) => {
        unsafe { & mut (* $crate::COMPONENTS). $name }
    };
}
/// Access a device from the global static registry
///
/// # Example
/// ```
/// let oled = device!(ctx, oled);
/// oled.clear();
/// ```
#[macro_export]
macro_rules! device {
    ($name:ident) => {
        unsafe { & mut (* $crate::DEVICES). $name }
    };
}
/// Execute a closure with mutable access to a component
///
/// # Example
/// ```
/// with_component!(ctx, red_led, |led| {
///     led.toggle();
/// });
/// ```
#[macro_export]
macro_rules! with_component {
    ($name:ident, | $var:ident | $body:block) => {
        { let $var = unsafe { & mut (* $crate::COMPONENTS). $name }; $body }
    };
}
/// Execute a closure with mutable access to a device
///
/// # Example
/// ```
/// with_device!(ctx, oled, |display| {
///     display.clear();
///     display.print(0, 0, "Hello!");
/// });
/// ```
#[macro_export]
macro_rules! with_device {
    ($name:ident, | $var:ident | $body:block) => {
        { let $var = unsafe { & mut (* $crate::DEVICES). $name }; $body }
    };
}
