// THIS IS A AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: espforge_codegen/src/lib.rs::generate_components_source

#![allow(unused_variables)]
#![allow(unused_imports)]
#![allow(unused_mut)]

use core::cell::RefCell;
use espforge_platform::esp_hal::gpio::{AnyPin, Input, Output, Level, Pin, Pull};
use espforge_platform::esp_hal::{Blocking, Async};
use espforge_platform::esp_hal::i2c::master::I2c;
pub struct PeripheralRegistry {
    pub i2c0: RefCell<I2c<'static, Blocking>>,
}
impl PeripheralRegistry {
    pub fn new(mut p: espforge_platform::esp_hal::peripherals::Peripherals) -> Self {
        let i2c0 = espforge_platform::esp_hal::i2c::master::I2c::new(
                p.I2C0,
                espforge_platform::esp_hal::i2c::master::Config::default()
                    .with_frequency(
                        espforge_platform::esp_hal::time::Rate::from_khz(100u32),
                    ),
            )
            .expect("Failed to initialize I2C")
            .with_sda(p.GPIO6)
            .with_scl(p.GPIO5);
        Self { i2c0: RefCell::new(i2c0) }
    }
}
pub struct Components {
    pub i2c_master: espforge_components::components::i2c::I2C,
}
impl Components {
    pub fn new(registry: &'static mut PeripheralRegistry) -> Self {
        let i2c_master = espforge_components::components::i2c::I2C::new(&registry.i2c0);
        Self { i2c_master }
    }
}
pub struct Devices {
    pub oled: espforge_devices::devices::ssd1306::device::SSD1306Device<
        espforge_components::components::i2c::I2C,
    >,
}
impl Devices {
    pub fn new(
        components: &'static mut Components,
        registry: &'static mut PeripheralRegistry,
        delay: &mut espforge_platform::delay::Delay,
    ) -> Self {
        let mut oled = espforge_devices::devices::ssd1306::device::SSD1306Device::new(
            components.i2c_master,
        );
        oled.init();
        Self { oled }
    }
}
pub struct Context {
    pub logger: espforge_platform::logger::Logger,
    pub delay: espforge_platform::delay::Delay,
}
