// USER-OWNED. This file is NOT regenerated by espforge. Edit freely.
// Embassy example: `setup` is async and receives the `Spawner` so it can spawn
// tasks; `forever` loops forever (ADR-008 app hooks).
use embassy_executor::Spawner;

pub async fn setup(ctx: &'static crate::Context, _spawner: Spawner) {
    let logger = &ctx.logger;
    logger.info("WiFi HTTP example starting");

    // `http` is the software-service component (ADR-012); it presumes the
    // implicit network Stack built from `esp32.wifi` in generated main.rs.
    // `get` takes `&self`, so a shared `&'static` reference is enough.
    let http = &ctx.components.http;

    match http.get("http://httpbin.org/ip").await {
        Ok(body) => {
            logger.info("HTTP GET ok:");
            logger.info(&body);
        }
        Err(e) => {
            logger.info("HTTP GET failed:");
            logger.info(&format!("{:?}", e));
        }
    }
}

pub async fn forever(_ctx: &'static crate::Context) {
    // nothing to poll; the network tasks run in the background.
}
