// USER-OWNED. This file is NOT regenerated by espforge. Edit freely.

pub fn setup(_ctx: &mut crate::Context) {
    // espforge wired your components/devices; access them via `crate::component!`/`crate::device!`.
}

pub fn forever(ctx: &mut crate::Context) {
    let led = crate::component!(ctx, red_led);
    loop {
        led.toggle();
        ctx.delay.delay_ms(1000);
    }
}
