//! In-tree device driver implementations (ADR-006). Terminal high-level drivers
//! that consume shared components by reference (ADR-003/008). Each device driver
//! is one module that declares its `Driver` trait impl, including the `construct`
//! snippet that tells the emitter how to wire the instance move-by-value. The
//! module list and `registry()` are generated by `build.rs` from the files in
//! this directory (design §9b).
include!(concat!(env!("OUT_DIR"), "/devices_gen.rs"));
