// USER-OWNED. This file is NOT regenerated by espforge. Edit freely.

pub fn setup(_ctx: &mut crate::Context) {
    // espforge wired your components/devices; access them via `crate::component!`/`crate::device!`.
}

pub fn forever(mut ctx: &mut crate::Context) {
    let mut led = crate::component!(ctx, red_led);
    loop {
        led.toggle();
        // Timing is application logic — espforge does not own it.
        // Insert a delay (e.g. `esp_hal::Delay::new().delay_ms(500)`) for a visible blink.
    }
}
