use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::error::Error;

pub fn render_main(crate_name: &str) -> Result<String, Box<dyn Error>> {
    let safe_crate_name = crate_name.replace('-', "_");
    let crate_ident = format_ident!("{}", safe_crate_name);

    let tokens: TokenStream = quote! {
        #![no_std]
        #![no_main]
        #[warn(unused_variables)]

        // Generated by espforge

        use esp_backtrace as _;
        use esp_hal::main;

        use #crate_ident::{Context, app};

        esp_bootloader_esp_idf::esp_app_desc!();

        #[main]
        fn main() -> ! {
            esp_println::logger::init_logger_from_env();
            esp_println::print!("\x1b[20h");

            let config = esp_hal::Config::default();
            let _peripherals = esp_hal::init(config);

            let mut ctx = Context::new();

            // Call setup
            app::setup(&mut ctx);

            loop {
                // Call forever loop
                app::forever(&mut ctx);
            }
        }
    };

    let syntax_tree = syn::parse2(tokens)?;
    Ok(prettyplease::unparse(&syntax_tree))
}

