//! In-tree component driver implementations (ADR-006). Each component driver is
//! one module that declares its `Driver` trait impl, including the `construct`
//! snippet that tells the emitter how to wire the instance move-by-value
//! (ADR-008). The module list and `registry()` are generated by `build.rs`
//! from the files in this directory — adding a driver is one new file, no edit
//! here (design §9b).
include!(concat!(env!("OUT_DIR"), "/components_gen.rs"));
