[package]
name = "espforge_configuration"
version = "0.3.2"
description = "Used by espforge project"
edition.workspace = true
license.workspace = true
readme.workspace = true 
keywords.workspace = true
categories.workspace = true
repository.workspace = true 
homepage.workspace = true
documentation.workspace = true

[dependencies]
espforge_common = { path = "../espforge_common", version = "0.1.6" }
espforge_esp32metadata = { version = "0.2.4", path = "../espforge_esp32metadata" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml_ng = "0.10"
anyhow = "1.0"
thiserror = "2.0"
inventory = "0.3"
proc-macro2 = "1.0"
quote = "1.0"
