[package]
name = "espforge_configuration"
version = "0.1.0"
edition = "2024"
description = "Used by espforge project"
license = "MIT"
readme = "../README.md"
keywords = ["esp32", "embedded", "hal", "framework", "esphome"]
categories = ["embedded", "hardware-support", "no-std"]
repository = "https://github.com/mohankumargupta/espforge"
homepage = "https://github.com/mohankumargupta/espforge"
documentation = "https://github.com/mohankumargupta/espforge"

[dependencies]
espforge_common = { path = "../espforge_common", version = "0.1.1" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml_ng = "0.10"
anyhow = "1.0"
thiserror = "2.0"
inventory = "0.3"
proc-macro2 = "1.0"
